# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:16
from __future__ import unicode_literals

from django.db import migrations

def return_data(filename):
    with open(filename) as infile:
        data = infile.readlines()
        rows = [line.split('|') for line in data]

    return rows

def add_raters(apps, schema_editor):
    rows = return_data('ml-100k/u.user')

    Rater = apps.get_model("mr_app", "Rater")
    for row in rows:
        Rater.objects.create(pk=row[0], age=row[1],
                             sex=row[2], occupation=row[3],
                             zipcode=row[4])

def add_movies(apps, schema_editor):
    col_names = ['title', 'release_date', 'video_date',
                 'url', 'unknown', 'action', 'adventure',
                 'animation', 'childrens', 'comedy', 'crime',
                 'documentary', 'drama', 'fantasy', 'film_noir',
                 'horror', 'musical', 'mystery', 'romance',
                 'scifi', 'thriller', 'war', 'western'
    ]

    with open('ml-100k/u.item', encoding='ISO-8859-1') as infile:
        data = infile.readlines()
        rows = [line.split('|') for line in data]

    Movie = apps.get_model("mr_app", "Movie")
    for row in rows:
        Movie.objects.create(pk=row[0], **dict(zip(col_names, row[1:])))


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_raters),
        migrations.RunPython(add_movies)
    ]
