# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 22:12
from __future__ import unicode_literals

from django.db import migrations

def add_ratings(apps, schema_editor):
    with open('ml-100k/u.data') as infile:
        data = infile.readlines()
        rows = [line.split('\t') for line in data]

    Rater = apps.get_model("mr_app", "Rater")
    Movie = apps.get_model("mr_app", "Movie")
    Rating = apps.get_model("mr_app", "Rating")
    for row in rows:
        rater = Rater.objects.get(pk=row[0])
        movie = Movie.objects.get(pk=row[1])
        Rating.objects.create(rater=rater, movie=movie,
                             rating=row[2], timestamp=row[3]
                             )


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0002_auto_20160225_2116'),
    ]

    operations = [
        migrations.RunPython(add_ratings)
    ]
