# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mr_app', '0006_auto_20160227_1944'),
        ('mr_app', '0007_auto_20160227_1944'),
    ]

    operations = [
    ]
